name = "shiny"
version = "0.1.0"
description = "A small validation library for Gleam that validates values through pipelines and accumulates problems."
licences = ["MIT"]
repository = { type = "github", user = "chozahe", repo = "shiny" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
